Make services "public":false by default for multi-tenancy
open-horizon/examples pull request #399
Opened 2020-11-17 05:07 UTC by clementkng

Partially addresses #356 

This commit changes the up-to-date services default to `"public": false` in their service definition files, so if people copy them by default they will not accidentally expose their services to people outside their org. The examples published to the IBM org must be public, so I also changed the `exchangePublish.sh` script to make the examples `"public": true` right before they are published. The approach is described in more detail [here](https://github.com/open-horizon/examples/issues/356#issuecomment-644694359).

Tested by:

1. Cloning the `examples` repo into `/tmp/open-horizon` (where `exchangePublish.sh` also pulls in the repo`)
2. Updating the up-to-date (ie everything except `wiotp` examples) services there to be `"public": false`
3. Running `./exchangePublish.sh -c myorg`
4. Checking all services listed under `hzn exchange service list IBM/` had `"public": true`. 

Signed-off-by: Clement Ng <clementdng@gmail.com>

2020-11-18 23:38 UTC, t-fine requested changes

2020-11-18 23:38 UTC, t-fine commented on tools/exchangePublish.sh
> +            cd horizon
Can this be worked into the file names?

2020-11-18 23:38 UTC, t-fine commented on tools/exchangePublish.sh
> +                    tmpfile=$(mktemp) && jq '.public = true' $sd > tmpfile && mv tmpfile $sd && rm "$tmpfile"
can we add one error check here `chk $? "modifying horizon metadata file $sd"`

2020-11-20 14:08 UTC, bmpotter reviewed
I think we should take a different approach to this. See my comment in https://github.com/open-horizon/examples/issues/356

2020-12-03 04:36 UTC, closed without merging